# Generated by Django 5.2.17 on 2026-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half day'), ('ABSENT', 'Absent')], default='PRESENT', max_length=16)),
                ('is_late', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('SELF', 'Self check-in'), ('ADMIN', 'Recorded by HR')], default='SELF', max_length=8)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
            },
        ),
    ]
