# Generated by Django 5.2.17 on 2026-10-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='total_break_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Sum of completed breaks; maintained by the break services, never sent by clients.'),
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('source', models.CharField(choices=[('ONLINE', 'Recorded online'), ('OFFLINE', 'Synchronised from offline mode')], default='ONLINE', max_length=8)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='employees.employee')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'started_at'], name='attendance__employe_19d019_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('employee',), name='break_one_active_per_employee'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='break_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('duration_seconds__isnull', True), ('ended_at__isnull', True), ('status', 'ACTIVE')), models.Q(('duration_seconds__isnull', False), ('ended_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='break_status_matches_end')],
            },
        ),
        migrations.CreateModel(
            name='OvertimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Company-local date the overtime started.')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('trigger', models.CharField(choices=[('AFTER_CHECKOUT', 'Started after normal check-out')], default='AFTER_CHECKOUT', max_length=16)),
                ('source', models.CharField(choices=[('ONLINE', 'Recorded online'), ('OFFLINE', 'Synchronised from offline mode')], default='ONLINE', max_length=8)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_sessions', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_sessions', to='employees.employee')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_25dfd4_idx'), models.Index(fields=['employee', 'started_at'], name='attendance__employe_32d2b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('employee',), name='overtime_one_active_per_employee'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='overtime_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('duration_seconds__isnull', True), ('ended_at__isnull', True), ('status', 'ACTIVE')), models.Q(('duration_seconds__isnull', False), ('ended_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='overtime_status_matches_end')],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_event_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('BREAK_START', 'Break started'), ('BREAK_END', 'Break ended'), ('OVERTIME_START', 'Overtime started'), ('OVERTIME_END', 'Overtime ended')], max_length=16)),
                ('channel', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline queue')], max_length=8)),
                ('client_timestamp', models.DateTimeField(blank=True, help_text='Time reported by the device.', null=True)),
                ('effective_at', models.DateTimeField(blank=True, help_text='Time the server applied the event at.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('CONFLICT', 'Conflict (not applied)'), ('REJECTED', 'Rejected (not applied)')], max_length=8)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='attendance__status_b74a8a_idx'), models.Index(fields=['channel', 'received_at'], name='attendance__channel_79b5c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_event_id'), name='sync_event_unique_per_user')],
            },
        ),
    ]
