# Generated by Django 5.2.17 on 2026-10-03 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_work_sessions'),
        ('employees', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFromHomeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'work-from-home request',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='overtimesession',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='overtimesession',
            name='overtime_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='overtimesession',
            name='overtime_status_matches_end',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='checkout_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Checked out by the employee'), ('GEO_FENCE_EXIT', 'Left the workplace area'), ('INACTIVITY_TIMEOUT', 'No activity'), ('ADMIN', 'Recorded by HR')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='location_issue',
            field=models.CharField(blank=True, help_text='Last location-monitoring problem.', max_length=24),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='location_issue_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='mode',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('WORK_FROM_HOME', 'Work from home')], default='OFFICE', max_length=16),
        ),
        migrations.AddField(
            model_name='breaksession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Ended by the employee'), ('ALLOWANCE_EXHAUSTED', 'Daily break allowance used up'), ('CHECKOUT', 'Ended at check-out')], max_length=20),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='decision_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='declaration_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Ended by the employee'), ('OVERTIME_INACTIVITY_TIMEOUT', 'No activity'), ('EXPIRED', 'Approval expired unused')], max_length=32),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='other_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='overtime_sessions', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='overtimesession',
            name='work_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='overtimesession',
            name='date',
            field=models.DateField(help_text='Company-local date of the overtime (request date).'),
        ),
        migrations.AlterField(
            model_name='overtimesession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimesession',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Running'), ('AUTO_STOPPED', 'Stopped automatically'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12),
        ),
        migrations.AddIndex(
            model_name='overtimesession',
            index=models.Index(fields=['status', 'date'], name='attendance__status_0c9ef2_idx'),
        ),
        migrations.AddConstraint(
            model_name='overtimesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('REQUESTED', 'APPROVED'))), fields=('employee',), name='overtime_one_open_request_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='overtimesession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), models.Q(('started_at__isnull', False), ('ended_at__gte', models.F('started_at'))), _connector='OR'), name='overtime_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='overtimesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('status__in', ['REQUESTED', 'APPROVED', 'REJECTED', 'CANCELLED'])), models.Q(('ended_at__isnull', True), ('started_at__isnull', False), ('status', 'ACTIVE')), models.Q(('duration_seconds__isnull', False), ('ended_at__isnull', False), ('started_at__isnull', False), ('status__in', ('COMPLETED', 'AUTO_STOPPED'))), _connector='OR'), name='overtime_status_matches_times'),
        ),
        migrations.AddField(
            model_name='workfromhomerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workfromhomerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='wfh_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.workfromhomerequest'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(condition=models.Q(('check_in__isnull', False), ('check_out__isnull', True)), fields=['last_activity_at'], name='attendance_open_activity'),
        ),
        migrations.AddIndex(
            model_name='workfromhomerequest',
            index=models.Index(fields=['status', 'date'], name='attendance__status_5d4403_idx'),
        ),
        migrations.AddIndex(
            model_name='workfromhomerequest',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_ca0db6_idx'),
        ),
        migrations.AddConstraint(
            model_name='workfromhomerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('employee', 'date'), name='wfh_one_open_request_per_day'),
        ),
    ]
