# Generated by Django 5.2.17 on 2026-10-05 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_geofence_wfh_overtime_workflow'),
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='When the browser last reported (evidence that it was still watching).', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_meeting_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Sum of completed meeting pauses (working time paused for a meeting).'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_non_working_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Sum of closed non-working periods (automatic check-out until resumed check-in).'),
        ),
        migrations.AlterField(
            model_name='breaksession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Ended by the employee'), ('ALLOWANCE_EXHAUSTED', 'Daily break allowance used up'), ('CHECKOUT', 'Ended at check-out'), ('MEETING', 'Ended when a meeting started')], max_length=20),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('OVERALL', 'Overall meeting'), ('SELECTED', 'Selected employee meeting')], max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='Optional. An active meeting ends automatically at this time.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('MANUAL', 'Ended by HR / Admin'), ('SCHEDULED_END', 'Reached its planned end time')], max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to='employees.employee')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('end_reason', models.CharField(blank=True, choices=[('MEETING_ENDED', 'Meeting ended'), ('CHECKOUT', 'Checked out during the meeting'), ('REMOVED', 'Removed from the meeting')], max_length=16)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_pauses', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_pauses', to='employees.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='attendance.meeting')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeWorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('USED', 'Used (checked in again)'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('checked_out_at', models.DateTimeField(help_text='The automatic check-out this request is about.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_requests', to='attendance.attendancerecord')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': 'resume-work request',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NonWorkingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('INACTIVITY_TIMEOUT', 'Checked out for inactivity')], default='INACTIVITY_TIMEOUT', max_length=20)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_working_periods', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_working_periods', to='employees.employee')),
                ('resume_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.resumeworkrequest')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'kind'], name='attendance__status_ce7c74_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'OVERALL'), ('status', 'ACTIVE')), fields=('kind',), name='meeting_one_active_overall'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('status__in', ['SCHEDULED', 'CANCELLED'])), models.Q(('ended_at__isnull', True), ('started_at__isnull', False), ('status', 'ACTIVE')), models.Q(('ended_at__gte', models.F('started_at')), ('started_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='meeting_status_matches_times'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end__isnull', True), ('scheduled_start__isnull', True), ('scheduled_end__gt', models.F('scheduled_start')), _connector='OR'), name='meeting_scheduled_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='meetingpause',
            index=models.Index(fields=['employee', 'started_at'], name='attendance__employe_8e20c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingpause',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('employee',), name='meeting_pause_one_active_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='meetingpause',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='meeting_pause_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='meetingpause',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_seconds__isnull', True), ('ended_at__isnull', True), ('status', 'ACTIVE')), models.Q(('duration_seconds__isnull', False), ('ended_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='meeting_pause_status_matches_end'),
        ),
        migrations.AddIndex(
            model_name='resumeworkrequest',
            index=models.Index(fields=['status', 'date'], name='attendance__status_b4c83f_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumeworkrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('employee',), name='resume_one_open_request_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='nonworkingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('attendance',), name='non_working_one_open_per_day'),
        ),
        migrations.AddConstraint(
            model_name='nonworkingperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_seconds__isnull', True), ('ended_at__isnull', True)), models.Q(('duration_seconds__isnull', False), ('ended_at__gte', models.F('started_at'))), _connector='OR'), name='non_working_end_after_start'),
        ),
    ]
