import type { Config } from "tailwindcss";
import roles from "./src/lib/theme-colors.json";

// Design tokens from the official Stitch export ("Obsidian Kinetic"):
// stitch_nexvra_hrms_enterprise_platform/*/code.html (tailwind config) and obsidian_kinetic/DESIGN.md.
// Colour roles, radius and spacing follow Stitch; `warning*` comes from DESIGN.md (amber for
// pending items). The type scale is Stitch's, with the largest sizes reduced ~2-8 px for a
// denser enterprise layout (owner request, 2026-10-03).
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      // Colour roles are CSS variables so light and dark themes share one set of class names
      // (values: src/app/theme.css, generated by scripts/build-theme.py).
      colors: Object.fromEntries(roles.map((name) => [name, `rgb(var(--nx-${name}) / <alpha-value>)`])),
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "1.5rem",
        "margin-md": "1.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1rem",
        "space-md": "0.75rem",
        "margin-lg": "2rem",
        margin: "1rem",
        "space-sm": "0.5rem",
        gutter: "1rem",
        "gutter-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter Variable", "Inter", "ui-sans-serif", "system-ui", "Segoe UI", "Arial", "sans-serif"],
        display: ["Space Grotesk Variable", "Space Grotesk", "Inter Variable", "ui-sans-serif", "sans-serif"],
        "code-mono": ["Inter Variable", "Inter", "sans-serif"],
        "label-lg": ["Inter Variable", "Inter", "sans-serif"],
        "label-md": ["Inter Variable", "Inter", "sans-serif"],
        "label-sm": ["Inter Variable", "Inter", "sans-serif"],
        "body-sm": ["Inter Variable", "Inter", "sans-serif"],
        "body-md": ["Inter Variable", "Inter", "sans-serif"],
        "body-lg": ["Inter Variable", "Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "data-metric": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "code-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-metric": ["24px", { lineHeight: "30px", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
