import type { Config } from "tailwindcss";

// Design tokens from the official Stitch export ("Obsidian Kinetic"):
// stitch_nexvra_hrms_enterprise_platform/*/code.html (tailwind config) and obsidian_kinetic/DESIGN.md.
// Colours, radius, spacing and the type scale are copied verbatim. Only `warning*` is added,
// taken from DESIGN.md ("Amber #FFD60A for pending approvals"), because the HTML has no amber token.
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#1e3700",
        "outline-variant": "#404a34",
        outline: "#8a957a",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#86dd00",
        "primary-fixed": "#9afc00",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant": "#47464a",
        "on-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        error: "#ffb4ab",
        "on-tertiary": "#303033",
        tertiary: "#ffffff",
        primary: "#ffffff",
        "on-secondary-fixed": "#1b1b1e",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        background: "#131313",
        "surface-tint": "#86dd00",
        surface: "#131313",
        "on-primary-fixed-variant": "#2d5000",
        "tertiary-container": "#e4e1e6",
        "on-secondary-container": "#b6b4b8",
        "secondary-fixed": "#e4e1e5",
        "primary-container": "#9afc00",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#303033",
        "surface-bright": "#3a3939",
        "tertiary-fixed": "#e4e1e6",
        "error-container": "#93000a",
        "surface-container": "#201f1f",
        "on-primary-fixed": "#0f2000",
        "on-primary-container": "#427000",
        "secondary-container": "#47464a",
        "secondary-fixed-dim": "#c8c6c9",
        "on-background": "#e5e2e1",
        secondary: "#c8c6c9",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#1b1b1e",
        "on-tertiary-container": "#656467",
        "on-surface-variant": "#bfcbae",
        "inverse-primary": "#3e6a00",
        "tertiary-fixed-dim": "#c8c5ca",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#47464a",
        warning: "#ffd60a",
        "warning-container": "#1f1600",
        "warning-outline": "#473400",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "1.5rem",
        "margin-md": "1.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1rem",
        "space-md": "0.75rem",
        "margin-lg": "2rem",
        margin: "1rem",
        "space-sm": "0.5rem",
        gutter: "1rem",
        "gutter-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter Variable", "Inter", "ui-sans-serif", "system-ui", "Segoe UI", "Arial", "sans-serif"],
        display: ["Space Grotesk Variable", "Space Grotesk", "Inter Variable", "ui-sans-serif", "sans-serif"],
        "code-mono": ["Inter Variable", "Inter", "sans-serif"],
        "label-lg": ["Inter Variable", "Inter", "sans-serif"],
        "label-md": ["Inter Variable", "Inter", "sans-serif"],
        "label-sm": ["Inter Variable", "Inter", "sans-serif"],
        "body-sm": ["Inter Variable", "Inter", "sans-serif"],
        "body-md": ["Inter Variable", "Inter", "sans-serif"],
        "body-lg": ["Inter Variable", "Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
        "data-metric": ["Space Grotesk Variable", "Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "code-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-metric": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
