# Generated by Django 5.2.17 on 2026-10-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_meeting_resume_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_CANCELLED', 'Leave cancelled'), ('PAYSLIP_PUBLISHED', 'Payslip published'), ('DOCUMENT_SHARED', 'Document shared'), ('TASK_ASSIGNED', 'Task assigned'), ('TASK_REMINDER', 'Task reminder'), ('TASK_RESPONSE', 'Task response'), ('TASK_COMPLETED', 'Task completed'), ('TASK_CANCELLED', 'Task cancelled'), ('MESSAGE_RECEIVED', 'Message received'), ('GROUP_MESSAGE_RECEIVED', 'Group message received'), ('GROUP_ADDED', 'Added to a group'), ('FILE_RECEIVED', 'File received'), ('OVERTIME_STARTED', 'Overtime started'), ('OVERTIME_COMPLETED', 'Overtime completed'), ('SYNC_STATUS', 'Offline sync status'), ('WFH_REQUESTED', 'Work from home requested'), ('WFH_APPROVED', 'Work from home approved'), ('WFH_REJECTED', 'Work from home rejected'), ('OVERTIME_REQUESTED', 'Overtime requested'), ('OVERTIME_APPROVED', 'Overtime approved'), ('OVERTIME_REJECTED', 'Overtime rejected'), ('OVERTIME_AUTO_STOPPED', 'Overtime stopped automatically'), ('ATTENDANCE_AUTO_CHECKOUT', 'Automatic check-out'), ('BREAK_AUTO_ENDED', 'Break ended automatically'), ('PASSWORD_CHANGED', 'Password changed'), ('MEETING_SCHEDULED', 'Meeting scheduled'), ('MEETING_STARTED', 'Meeting started'), ('MEETING_ENDED', 'Meeting ended'), ('MEETING_CANCELLED', 'Meeting cancelled'), ('RESUME_REQUESTED', 'Resume work requested'), ('RESUME_APPROVED', 'Resume work approved'), ('RESUME_REJECTED', 'Resume work rejected'), ('GENERAL', 'General')], default='GENERAL', max_length=32),
        ),
    ]
