# Generated by Django 5.2.17 on 2026-10-09 06:46

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def delivered_from_read(apps, schema_editor):
    """Existing members already received everything they read."""
    apps.get_model("messaging", "ConversationParticipant").objects.update(last_delivered_message_id=F("last_read_message_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('DIRECT', 'Direct message'), ('GROUP', 'Group')], default='DIRECT', max_length=6),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, help_text='Group name (groups only).', max_length=80),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_delivered_message_id',
            field=models.BigIntegerField(default=0, help_text="Delivery watermark: messages up to this id reached the member's app."),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=6),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='pair_key',
            field=models.CharField(blank=True, max_length=41, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'DIRECT'), ('pair_key__isnull', False)), models.Q(('kind', 'GROUP'), ('pair_key__isnull', True)), _connector='OR'), name='conversation_pair_key_matches_kind'),
        ),
        migrations.RunPython(delivered_from_read, migrations.RunPython.noop),
    ]
