// Generates src/components/ui/icons.tsx from Google Material Symbols (Outlined, weight 400),
// the icon set used by the Stitch design (stitch_nexvra_hrms_enterprise_platform).
// Material Symbols are Apache-2.0 licensed. Run `node scripts/build-icons.mjs` after editing ICONS;
// the generated file is committed, so builds need no network access.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const VERSION = "0.47.6";
const SOURCE = `https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@${VERSION}/outlined`;

// Component name -> Material Symbols glyph name.
const ICONS = {
  AlertTriangle: "warning",
  ArrowLeft: "arrow_back",
  ArrowRight: "arrow_forward",
  BarChart3: "analytics",
  Bell: "notifications",
  CalendarCheck: "event_available",
  CalendarDays: "calendar_month",
  CalendarRange: "date_range",
  Camera: "photo_camera",
  Check: "check",
  CheckCheck: "done_all",
  CheckCircle2: "check_circle",
  ChevronDown: "keyboard_arrow_down",
  ChevronLeft: "chevron_left",
  ChevronRight: "chevron_right",
  ClipboardCheck: "assignment_turned_in",
  Clock: "schedule",
  CloudOff: "cloud_off",
  Coffee: "coffee",
  Download: "download",
  ExternalLink: "open_in_new",
  Eye: "visibility",
  EyeOff: "visibility_off",
  FileText: "description",
  FolderShared: "folder_shared",
  Gavel: "gavel",
  History: "history",
  Inbox: "inbox",
  KeyRound: "key",
  LayoutDashboard: "dashboard",
  ListTodo: "checklist",
  LocateFixed: "my_location",
  LocationOff: "location_off",
  MapPin: "location_on",
  Monitor: "computer",
  MoreTime: "more_time",
  Hourglass: "hourglass_top",
  Home: "home_work",
  Sun: "light_mode",
  Lock: "lock",
  LogIn: "login",
  LogOut: "logout",
  Menu: "menu",
  MessageSquare: "chat_bubble",
  Moon: "dark_mode",
  Paperclip: "attach_file",
  Pencil: "edit",
  Play: "play_arrow",
  Plus: "add",
  Printer: "print",
  Receipt: "receipt",
  RefreshCw: "sync",
  RotateCcw: "replay",
  ScrollText: "receipt_long",
  Search: "search",
  Send: "send",
  ServerOff: "signal_disconnected",
  Settings: "settings",
  ShieldCheck: "verified_user",
  Square: "stop",
  Timer: "timer",
  Trash2: "delete",
  Upload: "upload",
  UserRound: "person",
  Users: "group",
  Wallet: "payments",
  Wifi: "wifi",
  X: "close",
  XCircle: "cancel",
};

async function glyph(name) {
  const res = await fetch(`${SOURCE}/${name}.svg`);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const svg = await res.text();
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length) throw new Error(`${name}: no path data`);
  return paths.join(" ");
}

const entries = await Promise.all(Object.entries(ICONS).map(async ([component, name]) => [component, name, await glyph(name)]));

const out = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Google Material Symbols, Outlined, weight 400 (Apache-2.0): the Stitch design's icon set.
import type { ReactElement, SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children">;
export type Icon = (props: IconProps) => ReactElement;

function make(d: string, name: string): Icon {
  function MaterialIcon({ className = "h-5 w-5", ...rest }: IconProps) {
    return (
      <svg
        viewBox="0 -960 960 960"
        fill="currentColor"
        aria-hidden="true"
        focusable="false"
        className={\`shrink-0 \${className}\`}
        data-icon={name}
        {...rest}
      >
        <path d={d} />
      </svg>
    );
  }
  return MaterialIcon;
}

${entries.map(([component, name, d]) => `export const ${component} = make(${JSON.stringify(d)}, ${JSON.stringify(name)});`).join("\n")}
`;

await writeFile(fileURLToPath(new URL("../src/components/ui/icons.tsx", import.meta.url)), out);
console.log(`Wrote ${entries.length} icons`);
