"""Generates the colour variables for light and dark themes (src/app/theme.css).

Dark = the official Stitch "Obsidian Kinetic" palette (unchanged). Light = the matching
Material 3 light roles for the same lime seed, so every component keeps its meaning in both
themes. Tailwind reads the variables (tailwind.config.ts: rgb(var(--nx-<name>) / <alpha>)).
Run: python scripts/build-theme.py
"""

from pathlib import Path

DARK = {
    "primary": "#ffffff", "on-primary": "#1e3700", "primary-container": "#9afc00", "on-primary-container": "#427000",
    "primary-fixed": "#9afc00", "primary-fixed-dim": "#86dd00", "on-primary-fixed": "#0f2000",
    "on-primary-fixed-variant": "#2d5000", "inverse-primary": "#3e6a00", "surface-tint": "#86dd00",
    "secondary": "#c8c6c9", "on-secondary": "#303033", "secondary-container": "#47464a",
    "on-secondary-container": "#b6b4b8", "secondary-fixed": "#e4e1e5", "secondary-fixed-dim": "#c8c6c9",
    "on-secondary-fixed": "#1b1b1e", "on-secondary-fixed-variant": "#47464a",
    "tertiary": "#ffffff", "on-tertiary": "#303033", "tertiary-container": "#e4e1e6", "on-tertiary-container": "#656467",
    "tertiary-fixed": "#e4e1e6", "tertiary-fixed-dim": "#c8c5ca", "on-tertiary-fixed": "#1b1b1e",
    "on-tertiary-fixed-variant": "#47464a",
    "error": "#ffb4ab", "on-error": "#690005", "error-container": "#93000a", "on-error-container": "#ffdad6",
    "background": "#131313", "on-background": "#e5e2e1", "surface": "#131313", "surface-dim": "#131313",
    "surface-bright": "#3a3939", "surface-container-lowest": "#0e0e0e", "surface-container-low": "#1c1b1b",
    "surface-container": "#201f1f", "surface-container-high": "#2a2a2a", "surface-container-highest": "#353534",
    "surface-variant": "#353534", "on-surface": "#e5e2e1", "on-surface-variant": "#bfcbae",
    "inverse-surface": "#e5e2e1", "inverse-on-surface": "#313030", "outline": "#8a957a", "outline-variant": "#404a34",
    "warning": "#ffd60a", "warning-container": "#1f1600", "warning-outline": "#473400",
    # Calm accents for dashboard figures (not part of the Stitch export; contrast >= 4.5:1 on cards, WCAG AA).
    "info": "#7cc4ff", "notice": "#f5b95f",
}

# Same roles on a light canvas. In this app "surface-container-lowest" is the page canvas and
# "-low" the card surface (see Stitch), so light mode puts white cards on a soft grey canvas.
LIGHT = {
    "primary": "#111310", "on-primary": "#0f2000", "primary-container": "#9afc00", "on-primary-container": "#2d5000",
    "primary-fixed": "#3e6a00", "primary-fixed-dim": "#86dd00", "on-primary-fixed": "#0f2000",
    "on-primary-fixed-variant": "#2d5000", "inverse-primary": "#86dd00", "surface-tint": "#3e6a00",
    "secondary": "#5d5f5a", "on-secondary": "#ffffff", "secondary-container": "#e1e3dc",
    "on-secondary-container": "#1a1c18", "secondary-fixed": "#e1e3dc", "secondary-fixed-dim": "#c5c7c0",
    "on-secondary-fixed": "#1a1c18", "on-secondary-fixed-variant": "#454743",
    "tertiary": "#1b1c18", "on-tertiary": "#ffffff", "tertiary-container": "#e4e1e6", "on-tertiary-container": "#47464a",
    "tertiary-fixed": "#e4e1e6", "tertiary-fixed-dim": "#c8c5ca", "on-tertiary-fixed": "#1b1b1e",
    "on-tertiary-fixed-variant": "#47464a",
    "error": "#ba1a1a", "on-error": "#ffffff", "error-container": "#ffdad6", "on-error-container": "#93000a",
    "background": "#f3f4f0", "on-background": "#1b1c18", "surface": "#f3f4f0", "surface-dim": "#dadad5",
    "surface-bright": "#d2d3ce", "surface-container-lowest": "#f3f4f0", "surface-container-low": "#ffffff",
    "surface-container": "#f0f1ec", "surface-container-high": "#e6e7e2", "surface-container-highest": "#dcddd7",
    "surface-variant": "#e1e4d6", "on-surface": "#1b1c18", "on-surface-variant": "#44483d",
    "inverse-surface": "#30312c", "inverse-on-surface": "#f2f1ec", "outline": "#6b7062", "outline-variant": "#c4c8ba",
    "warning": "#7a5900", "warning-container": "#fff4cc", "warning-outline": "#e9c46a",
    "info": "#005b94", "notice": "#8a4b00",
}

assert DARK.keys() == LIGHT.keys()


def rgb(hex_):
    hex_ = hex_.lstrip("#")
    return " ".join(str(int(hex_[i:i + 2], 16)) for i in (0, 2, 4))


def block(selector, palette, scheme):
    lines = [f"{selector} {{", f"  color-scheme: {scheme};"]
    lines += [f"  --nx-{name}: {rgb(value)};" for name, value in palette.items()]
    return "\n".join(lines + ["}"])


css = "\n\n".join([
    "/* GENERATED by scripts/build-theme.py - do not edit by hand. */",
    "/* Light is the base; `.dark` (on <html>, or on an element such as the sidebar) switches a subtree to dark. */",
    block(":root", LIGHT, "light"),
    block(".dark", DARK, "dark"),
]) + "\n"
root = Path(__file__).resolve().parent.parent
(root / "src" / "app" / "theme.css").write_text(css, encoding="utf-8")
(root / "src" / "lib" / "theme-colors.json").write_text(
    "[\n" + ",\n".join(f'  "{n}"' for n in DARK) + "\n]\n", encoding="utf-8"
)
print(f"Wrote {len(DARK)} colour roles")
