# Generated by Django 5.2.17 on 2026-10-02 08:39

import apps.accounts.usernames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Public @handle used to find people. Relationships use the internal id, never this.', max_length=30, null=True, unique=True, validators=[apps.accounts.usernames.validate_username]),
        ),
    ]
