# Generated by Django 5.2.17 on 2026-10-01 11:22

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('joining_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], max_length=16)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('NOTICE_PERIOD', 'Notice period'), ('EXITED', 'Exited')], default='ACTIVE', max_length=16)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to=apps.core.files.RandomUploadPath('employee_photos'))),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
    ]
