# Generated by Django 5.2.17 on 2026-10-01 11:22

import apps.organization.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'company',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='company_singleton')],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(blank=True, max_length=64, validators=[apps.organization.models.validate_timezone])),
                ('currency', models.CharField(blank=True, help_text='ISO 4217 code, e.g. USD', max_length=3)),
                ('working_days', models.JSONField(blank=True, help_text='Weekday numbers, 0=Mon … 6=Sun', null=True, validators=[apps.organization.models.validate_working_days])),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('late_grace_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_day_min_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('full_day_min_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('self_attendance_enabled', models.BooleanField(default=True)),
                ('leave_year_start_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('employee_document_upload_enabled', models.BooleanField(default=False)),
                ('deactivate_user_on_exit', models.BooleanField(default=False)),
                ('max_upload_size_mb', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
            ],
            options={
                'verbose_name_plural': 'company settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='company_settings_singleton'), models.CheckConstraint(condition=models.Q(('half_day_min_hours__isnull', True), ('full_day_min_hours__isnull', True), ('half_day_min_hours__lt', models.F('full_day_min_hours')), _connector='OR'), name='half_day_below_full_day')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional holidays do not reduce leave day counts.')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'name'), name='holiday_unique_date_name')],
            },
        ),
    ]
