# Generated by Django 5.2.17 on 2026-10-03 04:52

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_seed_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='break_allowance_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total break time allowed per working day, e.g. 60. Empty = no limit is applied.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('WORKING_HOURS', 'Working hours'), ('ATTENDANCE', 'Attendance'), ('BREAKS', 'Breaks'), ('LEAVE', 'Leave'), ('HOLIDAYS', 'Holidays'), ('CONDUCT', 'Employee conduct'), ('COMMUNICATION', 'Communication'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('body', models.TextField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Drafts are visible only to policy managers.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['is_published', 'category'], name='policy_published_category')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='policy_unique_title_ci')],
            },
        ),
    ]
