# Generated by Django 5.2.17 on 2026-10-03 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_break_allowance_and_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='geofence_max_accuracy_m',
            field=models.PositiveSmallIntegerField(default=100, help_text='Location readings less precise than this are not accepted for office check-in.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='geofence_radius_m',
            field=models.PositiveSmallIntegerField(default=20, help_text='Office check-in is allowed within this distance of the workplace (owner policy: 20 m).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='inactivity_timeout_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=30, help_text='Automatic check-out / overtime stop after this much inactivity (owner policy: 30). Empty = off.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='overtime_requires_approval',
            field=models.BooleanField(default=True, help_text='Overtime requests must be approved by HR or a Super Admin before they can start.'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='workplace_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='workplace_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='break_allowance_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=60, help_text='Total break time allowed per working day (owner policy: 60). Empty = no limit is applied.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AddConstraint(
            model_name='companysettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('workplace_latitude__isnull', True), ('workplace_longitude__isnull', True)), models.Q(('workplace_latitude__isnull', False), ('workplace_longitude__isnull', False)), _connector='OR'), name='workplace_both_coordinates_or_neither'),
        ),
    ]
