# Generated by Django 5.2.17 on 2026-10-01 11:22

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('OFFER_LETTER', 'Offer letter'), ('APPOINTMENT_LETTER', 'Appointment letter'), ('CERTIFICATE', 'Certificate'), ('ID_DOCUMENT', 'ID document'), ('PAYSLIP', 'Payslip'), ('EXPERIENCE_LETTER', 'Experience letter'), ('RELIEVING_LETTER', 'Relieving letter'), ('OTHER', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.core.files.RandomUploadPath('documents'))),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('visible_to_employee', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
