# Generated by Django 5.2.17 on 2026-10-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEDUCTION', 'Deducted on approval')], default='DEDUCTION', max_length=10)),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('balance_before', models.DecimalField(decimal_places=1, max_digits=6)),
                ('balance_after', models.DecimalField(decimal_places=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='leaves.leavebalance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_transaction', to='leaves.leaverequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gt', 0)), name='leave_txn_days_positive'), models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='leave_txn_never_negative')],
            },
        ),
    ]
